// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Suri.Models;

namespace Suri.Migrations
{
    [DbContext(typeof(SuriDbContext))]
    [Migration("20200417010636_AddPrioridades")]
    partial class AddPrioridades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        modelBuilder.Entity("Suri.Models.Actividades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actividad")
                        .IsRequired();

                    b.Property<string>("Asistente");

                    b.Property<bool>("Estado");

                    b.Property<DateTime>("FechaAsignacion");

                    b.Property<DateTime?>("FechaRealizacion");

                    b.Property<int>("LocalidadId");

                    b.Property<string>("MyUserId");

                    b.Property<string>("Nota");

                    b.Property<int>("PrioridadId");

                    b.Property<string>("UserId");

                    b.Property<string>("accion");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.HasIndex("MyUserId");

                    b.HasIndex("PrioridadId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("Suri.Models.Localidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CeldaId");

                    b.Property<string>("Coordenadas");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Localidades");
                });

           

            modelBuilder.Entity("Suri.Models.Prioridades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Prioridades");
                });




            modelBuilder.Entity("Suri.Models.Actividades", b =>
                {
                    b.HasOne("Suri.Models.Localidades", "Localidad")
                        .WithMany("Actividades")
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Suri.Models.MyUsers", "MyUser")
                        .WithMany("Actividades")
                        .HasForeignKey("MyUserId");

                    b.HasOne("Suri.Models.Prioridades", "Prioridad")
                        .WithMany("Actividades")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
